export const USER_REPOSITORY = 'IDENTITY_USER_REPOSITORY';
export const ROLE_REPOSITORY = 'IDENTITY_ROLE_REPOSITORY';
export const PASSWORD_POLICY = 'IDENTITY_PASSWORD_POLICY';
export const DOMAIN_EVENT_PUBLISHER = 'IDENTITY_DOMAIN_EVENT_PUBLISHER';
