export const APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY';
export const SLOT_REPOSITORY = 'SLOT_REPOSITORY';
export const CONSENT_CHECKER = 'CONSENT_CHECKER';
export const DOMAIN_EVENT_PUBLISHER = 'DOMAIN_EVENT_PUBLISHER';
